extra_srcs = [
    "../backtrace/src/**/*.rs",
    "../core/src/error.md",
    "../core/src/ffi/*.md",
    "../core/src/primitive_docs.rs",
    "../core/src/macros/panic.md",
    "../portable-simd/crates/core_simd/src/core_simd_docs.md",
    "../portable-simd/crates/std_float/**/*.rs",
    "../stdarch/crates/core_arch/src/core_arch_docs.md",
]

buildscript.run = false
cfgs = ["backtrace_in_libstd"]
rustc_flags = ["-Zforce-unstable-if-unmarked"]
preferred_linkage = "any"

['cfg(all(any(target_os = "linux", target_os = "macos"), target_arch = "x86_64"))']
env = { "STD_ENV_ARCH" = "x86_64" }
omit_deps = ["panic_abort"]
extra_deps = [":panic_unwind-0.0.0"]

['cfg(all(any(target_os = "linux", target_os = "macos"), target_arch = "aarch64"))']
env = { "STD_ENV_ARCH" = "aarch64" }
omit_deps = ["panic_abort"]
extra_deps = [":panic_unwind-0.0.0"]

['cfg(all(target_os = "linux", target_arch = "riscv64"))']
env = { "STD_ENV_ARCH" = "riscv64" }
omit_deps = ["panic_abort"]
extra_deps = [":panic_unwind-0.0.0"]

['cfg(windows)']
env = { "STD_ENV_ARCH" = "x86_64" }
omit_deps = ["panic_abort"]
extra_deps = [":panic_unwind-0.0.0"]
