buildscript.run = false

['cfg(all(target_arch = "x86_64", target_os = "linux"))']
cfgs = ["asm", "switchable_stack"]
[['cfg(all(target_arch = "x86_64", target_os = "linux"))'.cxx_library]]
name = "psm_s-linux-x86_64"
srcs = ["src/arch/x86_64.s"]
compiler_flags = ["-xassembler-with-cpp"]
headers = ["src/arch/psm.h"]

['cfg(all(target_arch = "aarch64", target_os = "linux"))']
cfgs = ["asm", "switchable_stack"]
[['cfg(all(target_arch = "aarch64", target_os = "linux"))'.cxx_library]]
name = "psm_s-linux-aarch64"
srcs = ["src/arch/aarch_aapcs64.s"]
compiler_flags = ["-xassembler-with-cpp"]
headers = ["src/arch/psm.h"]

['cfg(all(target_arch = "riscv64", target_os = "linux"))']
cfgs = ["asm", "switchable_stack"]
[['cfg(all(target_arch = "riscv64", target_os = "linux"))'.cxx_library]]
name = "psm_s-linux-riscv64"
srcs = ["src/arch/riscv64.s"]
compiler_flags = ["-xassembler-with-cpp"]
headers = ["src/arch/psm.h"]

['cfg(all(target_arch = "x86_64", target_os = "macos"))']
cfgs = ["asm", "switchable_stack"]
[['cfg(all(target_arch = "x86_64", target_os = "macos"))'.cxx_library]]
name = "psm_s-macos-x86_64"
srcs = ["src/arch/x86_64.s"]
compiler_flags = ["-xassembler-with-cpp"]
preprocessor_flags = ["-DCFG_TARGET_OS_macos"]
headers = ["src/arch/psm.h"]

['cfg(all(target_arch = "aarch64", target_os = "macos"))']
cfgs = ["asm", "switchable_stack"]
[['cfg(all(target_arch = "aarch64", target_os = "macos"))'.cxx_library]]
name = "psm_s-macos-aarch64"
srcs = ["src/arch/aarch_aapcs64.s"]
compiler_flags = ["-xassembler-with-cpp"]
preprocessor_flags = ["-DCFG_TARGET_OS_macos"]
headers = ["src/arch/psm.h"]

['cfg(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc"))']
cfgs = ["asm"]
[['cfg(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc"))'.cxx_library]]
name = "psm_s-windows-x86_64-msvc"
srcs = ["src/arch/x86_64_msvc.asm"]
headers = ["src/arch/psm.h"]

['cfg(all(target_arch = "x86_64", target_os = "windows", target_env = "gnu"))']
cfgs = ["asm"]
[['cfg(all(target_arch = "x86_64", target_os = "windows", target_env = "gnu"))'.cxx_library]]
name = "psm_s-windows-x86_64-gnu"
srcs = ["src/arch/x86_64_windows_gnu.s"]
compiler_flags = ["-xassembler-with-cpp"]
headers = ["src/arch/psm.h"]
