load(":defs.bzl", "constraint")

constraint(
    setting = "sysroot-deps",
    values = [
        # Crate must declare explicit dependencies on standard library. This is
        # enabled within standard library code.
        "sysroot-deps=explicit",
        # Crate implicitly receives access to standard library crates, such as
        # within compiler code and standard library build scripts.
        "sysroot-deps=implicit",
    ],
)

constraint(
    setting = "reindeer-universe",
    values = [
        # Transitive dependencies of rust/library/.
        "library",
        # Transitive dependencies of rust/compiler/.
        "compiler",
    ],
)

constraint(
    setting = "bootstrap-stage",
    values = [
        # Use stage0 (download) to build stage1 standard library and compiler.
        "stage1",
        # Use stage1 to build stage2 standard library and compiler.
        "stage2",
    ],
)

constraint(
    setting = "opt-level",
    values = [
        "opt-level=0",
        "opt-level=3",
    ],
)
